version: "2"
checks:
  method-lines:
    config:
      threshold: 100
  method-complexity:
    config:
      threshold: 30
  return-statements:
    config:
      threshold: 10
plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
exclude_patterns:
  - "rpc/"
  - "vendor/"
  - "examples"