[package]
name = "enseada"
version = "0.1.0"
authors = ["Matteo Joliveau <matteojoliveau@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
config = "0.9"
dotenv = "0.15"

[dependencies.log4rs]
version = "0.10"
features = [
"console_appender",
"compound_policy",
"delete_roller",
"fixed_window_roller",
"size_trigger",
"json_encoder",
"pattern_encoder",
"threshold_filter"
]