[package]
name = "enseada"
version = "0.1.0"
authors = ["Matteo Joliveau <matteojoliveau@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
config = "0.9"
dotenv = "0.15"
rustls = "0.17"
reqwest = { version = "0.10", features = ["json", "rustls-tls"] }
url = "2.1"
derivative = "1.0.3"
lazy_static = "1.4"
derive_more = "0.99"

[dependencies.log4rs]
version = "0.10"
features = [
"console_appender",
"compound_policy",
"delete_roller",
"fixed_window_roller",
"size_trigger",
"json_encoder",
"pattern_encoder",
"threshold_filter"
]