[package]
name = "enseada"
version = "0.1.0"
authors = ["Matteo Joliveau <matteojoliveau@gmail.com>"]
edition = "2018"
publish = false

[[bin]]
name = "enseada-server"
path = "src/main.rs"

[dependencies]
actix = "0.9"
actix-web = { version = "2.0", features = ["default", "rustls"] }
actix-rt = "1.0"
actix-files = "0.2"
actix-tls = { version = "1.0.0", features = ["rustls"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
config = "0.9"
dotenv = "0.15"
rustls = "0.16"
reqwest = { version = "0.10", features = ["json", "rustls-tls"] }
url = "2.1"
derivative = "1.0.3"
lazy_static = "1.4"
derive_more = "0.99"
yarte = { version = "0.7", features = ["with-actix-web"]  }

[dependencies.log4rs]
version = "0.10"
features = [
"console_appender",
"compound_policy",
"delete_roller",
"fixed_window_roller",
"size_trigger",
"json_encoder",
"pattern_encoder",
"threshold_filter"
]

[dependencies.oxide-auth-actix]
# We use this until this PR is merged, which updates ring to 0.16, which we need.
# https://github.com/HeroicKatora/oxide-auth/pull/73
git = "https://github.com/gzp-crey/oxide-auth"
rev = "7d67d8db70dfc9bf8c4d8ed550d22bf070132039"

[dependencies.oxide-auth]
# We use this until this PR is merged, which updates ring to 0.16, which we need.
# https://github.com/HeroicKatora/oxide-auth/pull/73
git = "https://github.com/gzp-crey/oxide-auth"
rev = "7d67d8db70dfc9bf8c4d8ed550d22bf070132039"

[build-dependencies]
yarte = { version = "0.7", features = ["with-actix-web"]  }